# Generated by Django 4.1.7 on 2023-05-22 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_logindb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logindb',
        ),
        migrations.RenameField(
            model_name='registrationdb',
            old_name='Name',
            new_name='User_Name',
        ),
    ]
