# Generated by Django 4.1.7 on 2023-06-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_cartdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdb',
            old_name='Product_Image',
            new_name='Products_Image',
        ),
    ]
