# Generated by Django 4.1.7 on 2023-06-08 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_rename_product_image_cartdb_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdb',
            name='Products_Image',
        ),
    ]
