# Generated by Django 4.1.7 on 2023-06-08 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_remove_cartdb_products_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdb',
            old_name='Price',
            new_name='Total_Price',
        ),
    ]
